{
  imports = [
    ./chat
    ./devtools
    ./easyeffects
    ./firefox
    ./games
    ./ghostty
    ./hyprland
    ./media
    ./productivity
    ./wezterm
    ./browsers.nix
    ./claude-desktop.nix
    ./gnome-keyring.nix
    ./graphics.nix
    ./kdeglobals.nix
    ./security.nix
    ./utilities.nix
  ];
}
