{
  imports = [
    ./browsers
    ./chat
    ./development
    ./easyeffects
    ./gaming
    ./hyprland
    ./media
    ./productivity
    ./terminals
    ./claude-desktop.nix
    ./gnome-keyring.nix
    ./graphics.nix
    ./kdeglobals.nix
    ./security.nix
    ./utilities.nix
  ];
}
