keys:
  - &admin_alexis age1pdsmvs22vq89pv0k6k9zfl3fk899cqehj2f7tx7j0tt6l66kuqssryqjlr
  - &host_hyperion age179gy6lwjjw3xm7wq6qxk4g0fh9skzujst7lau6qaw3356t6rddrsackn6f
  - &host_iserlohn age194seypvfeqj42g0zkzk4l56n4wcs843w5p3q46nkm0lgk6ldc39s6hrvw9
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_alexis
          - *host_hyperion
          - *host_iserlohn
