{
  imports = [
    ./dispatcharr
    ./jellarr
    ./autobrr.nix
    ./configarr.nix
    ./cross-seed.nix
    ./jellyfin.nix
    ./lidarr.nix
    ./prowlarr.nix
    ./qui.nix
    ./radarr.nix
    ./radarr-anime.nix
    ./readarr.nix
    ./readarr-audiobooks.nix
    ./romm.nix
    ./shoko.nix
    ./sonarr.nix
    ./sonarr-anime.nix
    ./torrents.nix
    ./zipline.nix
  ];
}
