b2:
    keyId: ENC[AES256_GCM,data:MUpYWztTu0FHBoMv+KjlAhUnd0ooGPaSDw==,iv:2+Xy2kVCjrnQ+umvK3xaJlElXMNdYxcjnMg6/VuhvIY=,tag:dhChXrBZWYQoSGCJwuPniA==,type:str]
    keyName: ENC[AES256_GCM,data:V6hxBm0z,iv:e8osnpmKgKUrTXm1UIIPzfaWOO6m6wKMedNCD3/zk+4=,tag:D5sMy7JzV+dO+GOf6ZfSlQ==,type:str]
    applicationKey: ENC[AES256_GCM,data:hWcFiSFLgR5HufSJIXqIN2imATrm9Hb5tKmxgJIG3Q==,iv:aNkEel6ZFYhc5B6WqBsAQ5Px5ZXX+K2FM01JyUhfbI8=,tag:AkbhipI5hxIGT1D+0mns1g==,type:str]
sops:
    age:
        - recipient: age1pdsmvs22vq89pv0k6k9zfl3fk899cqehj2f7tx7j0tt6l66kuqssryqjlr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrbXVCVTFuUU9aRU9nV2Y1
            WVRpN2NyU0dQdjZSTlZxUVM4OVU3MGdkaG5zCkxxVnVISmpqQnNYYUVJUlA5elhs
            SG5zbnk2L2hidW9NRW5ka0djZkVyR0UKLS0tIEZpSWp1cEw5alpYY0hoWWtXSllR
            N2VuZ0F2Q1FlK0crTjNrcW9GRXd6QW8KgcUtM5SQpdEnjoCLQTQlUEQRq1d+74pp
            E2LtkHSm9IElR8impHG8EugnHwnPNw8Qlnbgwbeow8CMJS/b2SwlTw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age179gy6lwjjw3xm7wq6qxk4g0fh9skzujst7lau6qaw3356t6rddrsackn6f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQaitPaU1yR0VBSllZUlhZ
            aFZTbmp5c290VW9nTnVCTzExQUFWWjc4L1I4ClNJdmRWQ2dQSGtaWnNKTldTL2dZ
            b1pobVNsWTNBTDA4WVFETUlWQkhmSFkKLS0tIGltbWFCaUxEUnFhOTFsdTlkQ20v
            eHNJUmJtV0loVkJMODlueUM2blozTkEK7asMre3gNRSsLPhF7H45v6O8ZaDIWvAh
            rAgw5QmnE2ujr1lfc+0oDSmNlzVkVzdpXHtXnvF3Yq4lvz7jqms4Aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-10T03:04:11Z"
    mac: ENC[AES256_GCM,data:ZOy9eL6CLOCvMM8hH2koYOLp4sX1gJYJP7TxvDFGIEvLV/QgR8hxM0PlA74WWgFjT0sgk2Eup3cuT6CnU9ccZ2te00uWxXia0/adfMhTW5AiEI3ik4egZPNNDlM4/MkMY5MEJhe+yoFNY6xf3UcB/Dx478r69Ed+PcrpiE4/+m4=,iv:R2YiszFBWpTR4D8/5OKr4EDbwq2rQ+3oAsqfR47zCAg=,tag:KSQBmJG3bzdW8rNo6YgtfA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.1
