mqtt_password: ENC[AES256_GCM,data:8a6gs2sp7OqtXxQrNaZf9FK53Yk+NTHPUBMk6iXTnaE=,iv:XtxVus784bLNmf/dryEJGZaOWZyYzl9idOH6mQBB5uc=,tag:ckjkL4J948ygvpLtrjnTag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQko5QmdiamlleDJQOXha
            MzN3Wkp6WlNmTVdXc1hhTzRxaS8zRlZscW1BClJkdUpHdHFmbHhKUDNLY01raUFY
            OHJHbHlmRDV4bnp3T2ZtZXFyakR6TDAKLS0tIGJMMERuZjZEK3VwZXIzbWx0QWhp
            VXgyWVpSZ2NqNWVRMURwM1FLV2h5TlkKVrdH1xRcheXoUAdTQ/HRgY9vnmz/Rpxn
            X4SRw+mXA4XkzitXzezNaXoNjdA7PtcAktVsVTp2CE1ERAwfEj903Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age179gy6lwjjw3xm7wq6qxk4g0fh9skzujst7lau6qaw3356t6rddrsackn6f
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFR0hUU1dMR0FTK3dpNE9Q
            UkVVYU9tbURmUzlQRnlSWXVwdThPR1VJbHlvCmN2S1UvbFJvcGZRZHRQVkloVDVZ
            TzI1ZFVhM2FuYitYZW1mbnFjVTdmbkEKLS0tIFpwSXFJVVNUSWVLRFFzaDJhNzFP
            TDV5L2daMU9hL3hRRkczM3lzWUl2Mm8KexVv3Hh/M9iXG6uNlty2ava48OXgN6Cp
            aFHj0dQTEvbEzhY9S/YiY7R/gTTX6qBbAKIhOL1HE5wC3++RfYsIWQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dln7w6394nl0rj63uq3slhp4l2v52mv75ty88xr8lgcrysxqqaeqkmkjd0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5YWVzbzd6NUZPT1BTNE5m
            WFlsUG5lVVR6MC92clNxSTZYY2I0ZkM3SEZjCjJFM1JkRUJIYnVQZlYvcGlHYlRz
            UFE5YmQxalRqbFR0SHVhNGYrd0dKV0UKLS0tIDRaYURneVFISDh1T1lJWXhNOG5G
            M0VJcHE0Ryt6cURBdDFwK1JyVlZYaE0K/ZXZxxDdje+Up8xTCWIqSg95ceSVSXu6
            aEEqMTaSp3S+wtO0HeyX8ME+nlLDBOL+dlIdaMe2w5jg5prEQ06yiA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kfrtrhkhvesrzv0dr28e9023w63zu7cy0s0tvy2avsx9kmyhwvaq205vjh
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRQmtwQU44T04waStsUHNy
            RmRvRUhvbVY0YjdVQ1FJd0pvWis4KzBBV2dnCkJxemtUZVRZRzg1ZzEybFVRbnoy
            RWY3UG8xTHlLUmVxemhnVHBYbGkxTzQKLS0tIDJ2eEFYRmczOGw0Q2NNRDk4dWlk
            a3lVY3V6QXFPdmdmZGRTV0FrWEx3SVEKOj7QKDICTmR0KQzGT2++WrPRifsK6mMe
            k/QAO1R/YkIUB+QdOdQ7vTuRXwyATNn5OsuCGC3aPnqaNI2ztYWUqQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15xaf2cq8ch0rnjm3jefss9un5ypllxfcu0m9kg0suj9au4gdc5fsfzxyx3
    lastmodified: "2026-09-11T20:37:36Z"
    mac: ENC[AES256_GCM,data:yEJjDGVtv8pNQA3JknaAs4n8M/Xu6vTP9KsOEdDgNNiaOBSBwbjhSIcImyyR8/N6Xj9NirAp5uQCiAb6ttHEY7HBJ+UDeJ2yInG7TZg50hboCRVKvyKehBdy7gF45kFr9L6R7jsMvCOMTPr5wLUkIGnmKQhQl7mUf6AQvJ4V3E4=,iv:uQ+asBomFXP9HXaWxCUyOItHFwuF1ejmkAHHahXPFe8=,tag:6gAXF48Uzo9tg5AIyCFUZA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
